import { YogaInstructor, YogaClass, Subscription, BlogPost } from './types';

export const mockInstructors: YogaInstructor[] = [
  {
    id: '1',
    name: 'Анна Соколова',
    bio: 'Практикую йогу более 10 лет. Сертифицированный инструктор по хатха-йоге и виньясе. Верю, что йога - это путь к гармонии тела и разума.',
    specialization: ['hatha', 'vinyasa'],
    experience: 10,
    certifications: ['RYT-500', 'Yoga Alliance', 'Хатха-йога (Ришикеш)'],
    socialLinks: {
      instagram: 'anna_yoga_samara',
      telegram: 'anna_yoga',
    },
  },
  {
    id: '2',
    name: 'Дмитрий Волков',
    bio: 'Специалист по инь-йоге и йога-нидре. Помогаю находить баланс и глубокое расслабление через практику.',
    specialization: ['yin', 'nidra'],
    experience: 7,
    certifications: ['RYT-300', 'Инь-йога (Сертификат)', 'Йога-нидра'],
    socialLinks: {
      instagram: 'dmitry_yin_yoga',
    },
  },
];

export const mockSchedule: YogaClass[] = [
  {
    id: '1',
    title: 'Утренняя хатха-йога',
    description: 'Мягкая практика для пробуждения тела и ума. Идеально для начала дня.',
    style: 'hatha',
    instructor: mockInstructors[0]!,
    dayOfWeek: 'monday',
    startTime: '08:00',
    duration: 90,
    level: 'beginner',
    maxParticipants: 15,
    currentParticipants: 8,
    price: 600,
  },
  {
    id: '2',
    title: 'Виньяса флоу',
    description: 'Динамичная практика с синхронизацией движения и дыхания.',
    style: 'vinyasa',
    instructor: mockInstructors[0]!,
    dayOfWeek: 'monday',
    startTime: '19:00',
    duration: 90,
    level: 'intermediate',
    maxParticipants: 15,
    currentParticipants: 12,
    price: 700,
  },
  {
    id: '3',
    title: 'Инь-йога',
    description: 'Медитативная практика с длительным удержанием асан для глубокого расслабления.',
    style: 'yin',
    instructor: mockInstructors[1]!,
    dayOfWeek: 'wednesday',
    startTime: '18:00',
    duration: 75,
    level: 'all',
    maxParticipants: 12,
    currentParticipants: 7,
    price: 650,
  },
  {
    id: '4',
    title: 'Йога-нидра',
    description: 'Практика осознанного расслабления. Йогический сон для восстановления сил.',
    style: 'nidra',
    instructor: mockInstructors[1]!,
    dayOfWeek: 'friday',
    startTime: '20:00',
    duration: 60,
    level: 'all',
    maxParticipants: 20,
    currentParticipants: 15,
    price: 500,
  },
  {
    id: '5',
    title: 'Хатха-йога для начинающих',
    description: 'Базовые асаны, дыхательные практики и расслабление.',
    style: 'hatha',
    instructor: mockInstructors[0]!,
    dayOfWeek: 'thursday',
    startTime: '18:30',
    duration: 90,
    level: 'beginner',
    maxParticipants: 15,
    currentParticipants: 10,
    price: 600,
  },
  {
    id: '6',
    title: 'Выходная практика',
    description: 'Расслабляющая практика для восстановления после рабочей недели.',
    style: 'hatha',
    instructor: mockInstructors[0]!,
    dayOfWeek: 'saturday',
    startTime: '11:00',
    duration: 90,
    level: 'all',
    maxParticipants: 15,
    currentParticipants: 13,
    price: 600,
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: '1',
    name: 'Пробный',
    description: 'Идеально для знакомства с йогой',
    classesCount: 4,
    validityDays: 30,
    price: 2200,
    features: ['4 занятия', 'Любые классы', 'Срок действия 30 дней'],
  },
  {
    id: '2',
    name: 'Стандарт',
    description: 'Оптимальный выбор для регулярной практики',
    classesCount: 8,
    validityDays: 30,
    price: 4000,
    discount: 10,
    features: ['8 занятий', 'Любые классы', 'Скидка 10%', 'Срок действия 30 дней'],
    popular: true,
  },
  {
    id: '3',
    name: 'Безлимит',
    description: 'Для тех, кто практикует каждый день',
    classesCount: 999,
    validityDays: 30,
    price: 6500,
    discount: 20,
    features: [
      'Безлимитное посещение',
      'Все классы',
      'Скидка 20%',
      'Приоритетная запись',
      'Бесплатная заморозка 7 дней',
    ],
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Йога для начинающих: с чего начать?',
    slug: 'yoga-for-beginners',
    excerpt:
      'Руководство для тех, кто только начинает свой путь в йоге. Основные принципы и советы.',
    content: `# Йога для начинающих

Начать практику йоги проще, чем кажется...`,
    author: mockInstructors[0]!,
    category: 'practice',
    tags: ['начинающим', 'основы', 'советы'],
    publishedAt: '2025-01-15',
    readingTime: 5,
  },
  {
    id: '2',
    title: 'Польза инь-йоги для современного человека',
    slug: 'benefits-of-yin-yoga',
    excerpt: 'Как медитативная практика помогает справиться со стрессом и восстановить энергию.',
    content: `# Инь-йога и её польза

В современном мире, полном стресса...`,
    author: mockInstructors[1]!,
    category: 'health',
    tags: ['инь-йога', 'здоровье', 'стресс'],
    publishedAt: '2025-01-10',
    readingTime: 7,
  },
  {
    id: '3',
    title: 'Дыхательные практики: основа йоги',
    slug: 'breathing-practices',
    excerpt: 'Пранаяма - искусство управления дыханием. Базовые техники для ежедневной практики.',
    content: `# Пранаяма

Дыхание - это мост между телом и разумом...`,
    author: mockInstructors[0]!,
    category: 'practice',
    tags: ['пранаяма', 'дыхание', 'техники'],
    publishedAt: '2025-01-05',
    readingTime: 6,
  },
];
